### PR TITLE
Fix for invalid authenticity token

### PR DESCRIPTION
**Pull request by raul-fuentes**
References
==========
* https://github.com/AyuntamientoMadrid/consul/issues/1298

Objectives
==========
* Fixed an error that occurred if someone who used the application in several tabs (and who had the session started), Log out in one tab, when trying to navigate to other private pages (in other tab), the server does not correctly recognize the action to log out and crashes

Visual Changes (if any)
=======================
* None

Notes
=====================
* Its the same error on [Agendas](https://github.com/AyuntamientoMadrid/agendas/pull/333) fixed by @vicentemendozam

### CODE REVIEW

**Comment by bertocq** [comment]
@raul-fuentes if I remove the ApplicationController#handle_unverified_request function, the test still passes 🤔 are we really testing something with it?

Remember to fix a bug first thing is to write an spec that reproduces the error scenario, then we can go for the code and be sure we're in the right path.

If this is not an issue you can tackle without access to preproduction/production servers for advanced research, please just skip it (I'm assuming you can see rollbar errors at least)

**Comment by raul-fuentes** [comment]
As can be seen on the trace shown on rollbar lines 1 and 2
```
1 File "/aytomad/app/participa/participacion/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/action_controller/metal/request_forgery_protection.rb" line 181 in handle_unverified_request
2 File "/aytomad/app/participa/participacion/shared/bundle/ruby/2.3.0/gems/actionpack-4.2.10/lib/action_controller/metal/request_forgery_protection.rb" line 209 in handle_unverified_request
```
And in the code we can find this lines

File 1
```
class Exception
  def initialize(controller)
    @controller = controller
  end

  def handle_unverified_request
    raise ActionController::InvalidAuthenticityToken
  end
end
```

File 2
```
if logger && log_warning_on_csrf_failure
   logger.warn "Can't verify CSRF token authenticity"
end
```
So I presume that handling manuanlly the handle_unverified_request and redirecting to new session should prevent more crashes on PRO.

Sadly the test does not reflect that asumption. 
I shall investigate further.

Sorry for the inconvenience

**Comment by raul-fuentes** [comment]
After a long research on  rollbar I found [this](https://rollbar.com/consul/Participacion/items/1215/occurrences/39432656551/).
Given an error on decide.madrid.es/account with PATCH all my suspicions fell on the authenticity_token.
Also all the errors have in common th POST or PATCH method, so I supose that they all will be forms.
So I proved it (This time works :) ) and added a solution

**Comment by MariaCheca** [comment]
Looks like a couple of Travis builds finished with a huge list of failed tests, after restarting them recently the result is the same. Can you check it @raul-fuentes?

The builds are:
https://travis-ci.org/AyuntamientoMadrid/consul/jobs/355961187
https://travis-ci.org/AyuntamientoMadrid/consul/jobs/355961197

**Comment by raul-fuentes** [comment]
Fixed!

**Comment by javierm** [comment]
Closing this one since it tests there are no exceptions when malicious users use the application. What we need to find out is when and why legitimate users get the exception; using several tabs is certainly not the only case :thinking_face:.

**Pull request closed without merging**
